### ISSUE TITLE
improve styling of site

### ISSUE THREAD

**Issue by seattleacademy** [seattleacademy/gayle#10]
Change coloring (first by adding Bootstrap classes to elements and then by changing styles.css), place in background images (like the SAAS logo, graduation cap, etc.) reduce spacing on lists, etc. to improve the look and functionality of the site.

**Comment by kaiasalverda** [comment]
I'll do this

**Comment by Ilong16** [comment]
I can work on this

**Comment by laurenpearl** [comment]
i can do this

**Comment by DavidKing206** [comment]
I can help do this

**Comment by seattleacademy** [comment]
Features implemented from all student work.
