### ISSUE TITLE
create better method for selecting classes

### ISSUE THREAD

**Issue by seattleacademy** [seattleacademy/gayle#12]
One method might be to have a right hand column with collapsible headings by department.  Students could then drag classes into the appropriate trimester to add them to terms.
Other methods are also possible.  Ideally put the method(s) developed into separate files that can be changed in index.html so that a/b testing can be made to check between different methods.

**Comment by WillMueller69** [comment]
theo 'says i have this one

**Comment by romansaladino** [comment]
William, please do your work, you are extremely off task
