### ISSUE TITLE
Add special halloween theme

### ISSUE THREAD

**Issue by seattleacademy** [seattleacademy/gayle#14]
Create separate halloween.css and halloween.js files with custom theming code and add links to them in index.html.  This code will add to or override existing code and the links can be commented out or removed to remove functionality.
Change colors, add background images, and some custom javascript (like falling leafs) to make the theme fun.  Great way to explore custom themes for our next project.

**Comment by kaiasalverda** [comment]
i'll do this

**Comment by laurenpearl** [comment]
i'll work on this

**Comment by seattleacademy** [comment]
Implemented in development version but not including in production.
