### ISSUE TITLE
Finish autofill feature

### ISSUE THREAD

**Issue by seattleacademy** [seattleacademy/gayle#16]
Add Advanced Algebra and Integrated Algebra course progression to autofill.  Also, add a select item for World Languages and rules from standard courses for Spanish, French, and Chinese at the different levels.  Html will be change in terms.html and javascript in autofill.js

**Comment by jordanhoward123** [comment]
i would like to try this

**Comment by jordanhoward123** [comment]
my code for the terms.html http://math.seattleacademy.org/jordanhoward/day21/terms.html

**Comment by jordanhoward123** [comment]
second link with improvements http://math.seattleacademy.org/jordanhoward/day22/js/autofill.js

**Comment by seattleacademy** [comment]
Good work, integrated into the code.
