### ISSUE TITLE
add favicon to project

### ISSUE THREAD

**Issue by seattleacademy** [seattleacademy/gayle#4]
Find a SAAS logo or another appropriate icon for a course planner.  Use a favicon web site to generate the icons an put in a directory img.  Then add the code to the index.html page to display the favicon.

**Comment by maxcook2002** [comment]
I can do this

**Comment by TroyGipson** [comment]
I would like to work on this

**Comment by oscarmestres** [comment]
I can work on this

**Comment by maxcook2002** [comment]
Done. What I did is I downloaded the SAAS logo off of the internet and put it in https://www.favicon.cc/ and turned it into a .ico file. Then I looked up how to add a favicon to a website an found this code: <link rel="icon" 
      type="image/png" 
      href="/somewhere/myicon.png" />
I changed it to 
<link rel="icon" 
      type="image/ico" 
      href="favicon.ico" />
Then I uploaded it to the server.
http://math.seattleacademy.org/maxcook/day19/index.html

**Comment by maxcook2002** [comment]
Done. What I did is I downloaded the SAAS logo off the internet and put it in https://www.favicon.cc/ to change it to a .ico file. Then I looked up how to add a favicon to a website an found this code:
<link rel="icon"
      type="image/png"
      href="/somewhere/myicon.png" />
I changed it to
<link rel="icon"
      type="image/ico"
      href="favicon.ico" />
Then I uploaded it to the server
math.seattleacademy.org/maxcook/day19/index.html

**Comment by maxcook2002** [comment]
Done. What I did is I downloaded the SAAS logo off the internet and put it in https://www.favicon.cc/ to change it to a .ico file. Then I looked up how to add a favicon to a website https://www.w3.org/2005/10/howto-favicon. I changed that code so it would work for my image and then I uploaded it to the server math.seattleacademy.org/maxcook/day19/index.html

**Comment by seattleacademy** [comment]
commit bdf2ad68a8c43e25d14f6da85775e2d157306614 @maxcook2002
