### ISSUE TITLE
add requirements for all classes

### ISSUE THREAD

**Issue by seattleacademy** [seattleacademy/gayle#5]
initially, create separate versions of reqs.js for each class (reqs2022.js, reqs2021.js, etc.)  Edit index.js to select the appropriate class.
Then, add a menu to the requirements card to select the appropriate class.  Default to 2022 requirements which are the most expansive.

**Comment by celestemccallcromer** [comment]
i can do this

**Comment by savannahwestra** [comment]
I will do this.

**Comment by sashapoll** [comment]
I will do this
