### ISSUE TITLE
add public school graduation requirements

### ISSUE THREAD

**Issue by seattleacademy** [seattleacademy/gayle#6]
Research the requirements to get a public school diploma in Washington state.  Make a version of reqs.js called reqspublic.js that can be used to see progress for a public school requirements diploma.  Test by changing the reference in index.html

**Comment by romansaladino** [comment]
I can do this

**Comment by WillMueller69** [comment]
I got this too

**Comment by seattleacademy** [comment]
Added in development version but removed from production.
