### ISSUE TITLE
update nav menu with appropriate links

### ISSUE THREAD

**Issue by seattleacademy** [seattleacademy/gayle#7]
Edit the nav menus to link to various helpful resources such as a link to graduation requirements, help file, etc.

**Comment by isabelsiebrecht** [comment]
I can try to work on this. Here is a link to what I worked on http://math.seattleacademy.org/isabelsiebrecht/day19/nav.html?#

**Comment by jordanhoward123** [comment]
i can do this

**Comment by Ilong16** [comment]
I can work on this

**Comment by oscarmestres** [comment]
I can work on this

**Comment by jordanhoward123** [comment]
Here is my link to the draft http://math.seattleacademy.org/jordanhoward/day19/nav.html#

I added a sites that included the overview of the academics, arts, and sports. I did that by butting the link in the href and putting the title after. I applied these under the drop-down menu and the nav-link.

**Comment by seattleacademy** [comment]
Implemented from all student's contributions.
